import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { auth } from "@/auth";
import { ThemeProvider } from "next-themes";

const poppins = Poppins({
	subsets: ["latin"],
	weight: ["300", "500", "700", "900"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await auth();
	return (
		<html lang="en">
			<body className={poppins.className}>
				<ThemeProvider attribute="class">
					<Navbar user={session?.user!} />
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
